# RUNTIME ==========
seed: 42


# MODEL ==========
model:
  name: dae
  params:
    input_dim: 28
    latent_dim: 256
    output_dim: 28
    hidden_dim: [64, 128]
    dropout: 0.2


# PIPELINE PACKAGE ==========
split:
  ratio:
    trn: 0.8
    val: 0.2
  shuffle: True

dataloader:
  batch_size: 128
  shuffle: True


# TRAINER PACKAGE ==========
trainer:
  num_epochs: 100

loss:
  name: mse

optimizer:
  name: adamw
  params:
    lr: 0.001
    weight_decay: 0.001

monitor:
  delta: 0.0001
  patience: 5
  warmup: 10


# EVALUATOR PACKAGE ==========
evaluator:
  percentile: [0.950, 0.955, 0.960, 0.965, 0.970, 0.975, 0.980, 0.985, 0.990, 0.995]